name: $(BuildID)

trigger:
  - master

pr: none

variables:
  DockerImageName: dixaba/test

pool: 
  vmImage: ubuntu-latest

jobs:
  - job: latest
    timeoutInMinutes: 0
    steps:

    - task: Bash@3
      displayName: Bash
      inputs:
        targetType: 'inline'
        script: |
          chmod +x build.sh
          REPONAME=$(DockerImageName) ./build.sh latest-buildx86
          REPONAME=$(DockerImageName) ./build.sh latest tag
          docker rmi $(DockerImageName):latest-buildx86

    - template: push_images.yml
      parameters:
        DockerImageName: $(DockerImageName)


  - job: latestx64
    timeoutInMinutes: 0
    steps:

    - task: Bash@3
      displayName: Bash
      inputs:
        targetType: 'inline'
        script: |
          chmod +x build.sh
          REPONAME=$(DockerImageName) ./build.sh latest-buildx64
          REPONAME=$(DockerImageName) ./build.sh latest-x64 tag
          docker rmi $(DockerImageName):latest-buildx64

    - template: push_images.yml
      parameters:
        DockerImageName: $(DockerImageName)

  - job: both
    timeoutInMinutes: 0
    dependsOn:
      - latest
      - latestx64
    steps:

    - task: Bash@3
      displayName: Bash
      inputs:
        targetType: 'inline'
        script: |
          chmod +x build.sh
          REPONAME=$(DockerImageName) ./build.sh latest-both tag

    - template: push_images.yml
      parameters:
        DockerImageName: $(DockerImageName)